# Generated by Django 4.1.6 on 2023-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
